### PR TITLE
Added Settings styling

### LINKED ISSUE #97: Creëren van een Settings-pagina

### PR DESCRIPTION
**Pull request by noelherwig**

### CODE REVIEW

**Review by MaxAltena — CHANGES_REQUESTED** [review]
Changes to be made:
- When clicking on icons in the inputs, the focus is not correctly handled.
- Input fields have type of `search` instead of corresponding types such as; `text` and `email`.
- The ability to differentiate between first and last name when the form is filled out is not there.
- Toggle should be on the right rather then on the left of the label.
- Links at the bottom of the page are not clickable.

**Review by MaxAltena — CHANGES_REQUESTED** [review]
Reviewing this again; looking back at the changes to be made section at https://github.com/de-sigaar/ikwil-app/pull/94#pullrequestreview-388147145

Changes to be made:
- [x] When clicking on icons in the inputs, the focus is not correctly handled. *No focus at all on icon clicks*
- [X] Input fields have type of search instead of corresponding types such as; text and email. *Additionally an [autocomplete](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete) attribute?*
- [x] The ability to differentiate between first and last name when the form is filled out is not there.
- [X] Toggle should be on the right rather then on the left of the label.
- [ ] Links at the bottom of the page are not clickable.

**Comment by BroodBalloon** [comment]
max-width: 400px 
and 
margin: auto
could be considered adding to the wrapper for better desktop experience.

**Review by MaxAltena — CHANGES_REQUESTED** [review]
Changes to be made:
- [x] ESLint/Prettier not run on commit -> Please fix whitespace issues
- [x] Privacy link goes to `/login` instead of `/privacy-policy`
- [ ] Profile is read, but not used anywhere. Possible to make settings actually work?
- [x] Settings shouldn't show when not logged in. @MaxAltena will fix this.

**Review by MaxAltena — APPROVED** [review]

**Pull request merged**
